print("==WESTERN GENERATOR==")
print()
print("Welcome to the Western Generator!")
print("This program will generate a Western story based on your choices")
print()
print("Please enter the following information:")
print()
CowboyName = input("What is your Cowboy name? ")
CowboyNickname = input("What is your Nickname? ")
CowboyHorse = input("What is the name of your horse? ")
CowboyProfession = input("What is your cowboy's profession? ")
CowboyTown = input("What is the name of your town? ")
TownSaloon = input("What is the name of the towns saloon? ")
TownSheriff = input("Who is your town's sheriff? ")
RivalCowboy = input("What is the name of your rival/enemy? ")
RivalNickname = input("What is your rival/enemy's nickname? ")
RivalGangName = input("What is the name of your rival/enemy's gang? ")
StandOffReason = input("What is the reason for the shoot out? ")
DayOfShootOut = input("On what day is the shoot out taking place? ")
TimeOfShootOut = input("What time is the shoot out? ")
CowboyWeapon = input("What is your cowboy's weapon of choice? ")
RivalCowboyWeapon = input("What is your rival's weapon of choice? ")
print()
print()
print()
print()
print()
print("One day in the small town of", CowboyTown, " a young", CowboyProfession,)
print("and his horse", CowboyHorse)
print("Rode into town, looking for a place to quench his thirst")
print("Then he stopped, to see the", TownSaloon, " saloon for a drink")
print("unopposed he drinks his whiskey, suddenly the saloon doors flies")
print("open, mouths agasp everyone is silently staring, it's",RivalCowboy)
print("and his gang the", RivalGangName, "gang")
print("Gimme a shot of bourbon, barkeep and the rest some lemonade")
print("to which the rest of his gang give each other puzzled looks")
print(RivalCowboy,"gives", CowboyName, "a funny look,'what you doing in my town boy?'")
print(CowboyName,"'i'm just...'',don't speak boy, 'do you know who i am?' ")
print(CowboyName,"just stares silently, 'they call me'", RivalNickname, RivalCowboy)
print("'hey i know you, were'nt you the guy who", StandOffReason)
print(RivalCowboy, "stands up knocking his and his gangs drinks over")
print("'right thems fighting words boy'")
print("Then Sheriff", TownSheriff, "bursts through the saloon doors")
print("'Don't you be causing trouble in my town again", RivalNickname)
print("'I'll get you boy, you see if i don't', meet me at")
print(TimeOfShootOut, "'on'", DayOfShootOut,)
print("'I'm just a humble", CowboyProfession, "'but i'll be there")
print("then", RivalNickname, "leaves with his gang")
print("'I'll see you next time boy', looking angry")
print("then the bar keep looks at", CowboyName, "sternly,'I hope you know what your doing boy'")
print("then the day comes, our hero", CowboyName, "get's on his horse")
print(CowboyHorse,"and get's ready for a busy day ahead")
print("the day finally comes, our hero", CowboyName, "has to find a weapon")
print("'What am i going to use for a weapon'", CowboyHorse, "?")
print("'I don't have a gun', then suddenly our hero sees something")
print("out the corner of his eye")
print("'that's it i'll use", CowboyWeapon, "as a weapon")
print("Then from the yonder comes", RivalCowboy)
print("'Damn it i forgotten my gun', says", RivalCowboy)
print("Then proceeds to pull out", RivalCowboyWeapon)
print("'never failed me before'")
print("both hero and villain stand opposite each other")
print("'right boy on the count of three'")
print("'1,2,...3'")
print("then just as", RivalCowboy, "goes to draw his", RivalCowboyWeapon,)
print(CowboyHorse,"proceeds to let out a loud fart, making")
print(RivalCowboy,"jump and drop his", RivalCowboyWeapon)
print("our hero then pulls out his", CowboyWeapon,"and, BANG!,")
print(RivalCowboy,"then drops to his knees cluthing his chest, and falls foward")
print("then the crowd cheer and runs over to our hero")
print(TownSheriff,"then grabs our hero by the hand")
print("and raises it,'today is a good day for our town'")
print("Then for ever more", CowboyName, "was forever known by the nickname")
print(CowboyNickname,"of", CowboyTown)
print("along with his horse", CowboyHorse, "had the freedom of the town")
print()
("==THE END==")